### ISSUE TITLE
add cli flag for insecure connections

### ISSUE THREAD

**Issue by joek-office** [gtema/openstack#308]
When working with an internal test openstack without official certificates, the auth won't be able due to the invalid certificates.
Is it possible to add a -i/--insecure option to the command line parameters do drop the certificate validation?

**Comment by gtema** [comment]
https://docs.openstack.org/openstacksdk/latest/user/config/configuration.html#ssl-settings

From that doc at the moment only `cacert` is supported. Please inform if you need support for `verify: false`

**Comment by gtema** [comment]
What is the format of the ca cert: pem or der?

**Comment by joek-office** [comment]
the format is pem

**Comment by gtema** [comment]
I strongly assume you use not the latest version (`osc --version`). In 0.5.2 exactly that was addressed and it works for me with self-signed Cloud-in-a-box installation. Anyway, https://github.com/gtema/openstack/pull/309 would add also `verify: false`. But again - it is better to have cacert rather than skip verification

**Comment by joek-office** [comment]
yes was on version 0.5.1. will now update and test again

**Comment by joek-office** [comment]
with version 0.5.2 the cacert option is available. 
Now all went as expected. 
Thank you
